# Generated by Django 6.0 on 2025-12-25 16:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
