# Generated by Django 6.0 on 2025-12-25 16:32

import resume.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_resume_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='expires_at',
            field=models.DateTimeField(default=resume.models.default_expiry),
        ),
        migrations.AlterField(
            model_name='resume',
            name='original_file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
