# Generated by Django 6.0 on 2025-12-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_resume_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.CharField(max_length=500),
        ),
    ]
